port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
redis:
  address: localhost:6379
keys:
  APIdJhgr9E3fvSp: TjSg8VhSIMnNrCBbhvXgSNqCjzxJXYsLNJEnwqSAhqKR
logging:
  level: info
