api_key: APIdJhgr9E3fvSp
api_secret: TjSg8VhSIMnNrCBbhvXgSNqCjzxJXYsLNJEnwqSAhqKR
ws_url: ws://localhost:7880
redis:
  address: localhost:6379
sip_port: 5060
rtp_port: 10000-20000
use_external_ip: true
logging:
  level: info
